### ISSUE TITLE
Cannot read properties of undefined (reading 'graphicType')

### ISSUE THREAD

**Issue by imedia3** [ImagingDataCommons/slim#256]
Getting errors when trying to Draw ROI's:

> ### An unexpected error occured in the App component
> Cannot read properties of undefined (reading 'graphicType')
> #### Component Stack:
> TypeError: Cannot read properties of undefined (reading 'graphicType') at n.value (https://slim.url/static/js/687.0c899362.chunk.js:1:123697) at Fl (https://slim.url/static/js/main.336fd26c.js:2:238843) at Nl 
> (https://slim.url/static/js/main.336fd26c.js:2:238639) at Cu (https://slim.url/static/js/main.336fd26c.js:2:282298) at bc 
> (https://slim.url/static/js/main.336fd26c.js:2:270269) at gc (https://slim.url/static/js/main.336fd26c.js:2:270197) at mc 
> (https://slim.url/static/js/main.336fd26c.js:2:270060) at oc (https://slim.url/static/js/main.336fd26c.js:2:266840) at ac 
> (https://slim.url/static/js/main.336fd26c.js:2:265391) at E (https://slim.url/static/js/main.336fd26c.js:2:301646)

### What's Been Done:
1. git clone https://github.com/ImagingDataCommons/slim/ slim && cd slim
2. Connected to Orthanc/DICOMweb in `public/configs/local.js`
![image](https://github.com/user-attachments/assets/0c7c2fe9-572a-4cf6-a3e2-2c7f9f82499d)

3. Started the application with: `docker compose up -d --build`  OR `yarn start` 
4. Accessed the Web UI, opened a study (any), and attempted to draw an ROI.
Result: The UI crashed with multiple pop-up errors.
Example:
![image](https://github.com/user-attachments/assets/6cbd07bc-d484-49ae-b8ce-d6f7efa284b4)

Is it a Bug, or we do wrong something? Few days ago it was working fine and I was able to draw ROIs (actually I had problems before some fixes on Nginx reverse-proxy for Orthanc side, but now without any changes it's stopped to work

**Comment by pedrokohler** [comment]
@imedia3 can you share the console logs of and right before the error occurs?

**Comment by pedrokohler** [comment]
@imedia3 if you could share a couple of sample studies where this happens it would also be very helpful.

**Comment by imedia3** [comment]
@pedrokohler 
1. Entered any study, the Network tab has only 200/Finished/and two 304 statuses
![image](https://github.com/user-attachments/assets/8a9a8ebf-a8f9-4607-8608-0bbc47408775)
* The Network tab has only 200/Finished/and two 304 statuses, 
2. Now I click "Draw ROI" > Choosing Polygon (result is not depends on chose) > Clicking on "picture" leads to Pop-up error on each click, as below
![image](https://github.com/user-attachments/assets/f9336536-cbf9-43e9-9d13-10f4825511d0)
3. If I finishing drawing ROI, the page shown as crashed, as below, with this console output:
![image](https://github.com/user-attachments/assets/d532fa05-b9c0-47d3-bbad-0cc5bbf85dc1)


Some new details, 
- at the same time all ROI's work without errors in another, stage environment under **nginx** reverse-proxy, with exact same config and data source, it seems stable for few days.
- in Dev env (which is issue about), it worked from the deploy, then stopped to work without any actions, it is proxied by Caddy, tried to play with headers, no result. 
- 3rd case is in another environment, with 100% different orthanc/dicomWeb data. Proxied with Nginx too. ROI worked few days, then unexpectedly stopped to work with same errors mentioned above, but after 1 day of unavailability it started to work again, without Any actions to Nginx or Slim docker images (even no restarts)

**Comment by fedorov** [comment]
@imedia3 unfortunately, the resources we have available for maintenance of Slim are very limited right now. The only project that is funding Slim maintenance at this time is Imaging Data Commons, where the main use case is support of visualization of images and annotations hosted via Google Healthcare DICOMweb implementation. Creation of annotations is not a feature we are actively using or maintaining at this time. We are actively looking for opportunities to secure resources to allow us to do more. We can spend only minimal time trying to investigate this issue, and @pedrokohler did that.

You are welcome to contribute to Slim by submitting a PR if you manage to identify and address the underlying issue.
